/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Subcall,
  SubcallInterface,
} from "../../../../@oasisprotocol/sapphire-contracts/contracts/Subcall";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "status",
        type: "uint64",
      },
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "AccountsTransferError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "status",
        type: "uint64",
      },
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "ConsensusDelegateError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "status",
        type: "uint64",
      },
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "ConsensusTakeReceiptError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "status",
        type: "uint64",
      },
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "ConsensusUndelegateError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "status",
        type: "uint64",
      },
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "ConsensusWithdrawError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    name: "CoreCallDataPublicKeyError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    name: "CoreCurrentEpochError",
    type: "error",
  },
  {
    inputs: [],
    name: "IncompleteParse",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidReceiptId",
    type: "error",
  },
  {
    inputs: [],
    name: "MissingKey",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "receiptId",
        type: "uint64",
      },
    ],
    name: "ParseReceiptError",
    type: "error",
  },
  {
    inputs: [],
    name: "RoflOriginNotAuthorizedForApp",
    type: "error",
  },
  {
    inputs: [],
    name: "SubcallError",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "receiptKind",
        type: "uint256",
      },
    ],
    name: "TakeReceiptKindOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenNameTooLong",
    type: "error",
  },
  {
    inputs: [],
    name: "WrongMapSizeError",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212204f71ed050e07dbedfb82e2fef9b6642d578f2ec093dabe28e963d64520e8e4c464736f6c63430008130033";

type SubcallConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SubcallConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Subcall__factory extends ContractFactory {
  constructor(...args: SubcallConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Subcall & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Subcall__factory {
    return super.connect(runner) as Subcall__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SubcallInterface {
    return new Interface(_abi) as SubcallInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Subcall {
    return new Contract(address, _abi, runner) as unknown as Subcall;
  }
}
